# 1. Definiujemy, w jakim obrazie domyślnie uruchamiają się skrypty
# Używamy tego samego, co w Dockerfile!
image: mcr.microsoft.com/playwright:v1.50.0-jammy

# 2. Definiujemy etapy (Stages)
stages:
  - test

# 3. Definiujemy Joba "e2e-tests"
playwright-job:
  stage: test
  
  # 4. Serwisy poboczne (Baza Danych)
  services:
    - name: postgres:latest
      # WAŻNE: To jest nazwa hosta, pod którą baza będzie widoczna dla testów!
      alias: postgres-db 
      # Environment variables DLA BAZY (żeby wiedziała jak wstać)
      command: ["postgres", "-c", "fsync=off"] # Opcjonalna optymalizacja dla CI (szybciej, mniej bezpiecznie)

  # 5. Zmienne globalne (dostępne dla testów i serwisów)
  variables:
    # Konfiguracja Bazy (musi pasować do tego co wyżej)
    POSTGRES_DB: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: mysecretpassword
    
    # Konfiguracja Testów
    DB_HOST: postgres-db   # <-- Odwołujemy się do aliasu serwisu!
    DB_USER: postgres
    DB_PASSWORD: mysecretpassword
    BASE_URL: https://jsonplaceholder.typicode.com
    
    # Cache Playwrighta (żeby nie instalować przeglądarek jeśli są w obrazie)
    PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'

  # 6. Cache (przyspieszamy npm install)
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/

  # 7. Właściwe kroki
  script:
    - npm ci --cache .npm --prefer-offline
    - npx playwright test

  # 8. Raporty
  artifacts:
    when: always
    paths:
      - playwright-report/
      - test-results/
    expire_in: 30 days